- name: disable nodejs
  ansible.builtin.shell: dnf module disable nodejs -y

- name: enable nodejs:18
  ansible.builtin.shell: dnf module enable nodejs:18 -y

- name: Install NodeJS
  ansible.builtin.dnf:
    name: nodejs
    state: installed

- name: App Pre-Req
  ansible.builtin.include_tasks: "app-prereq.yml"

- name: Install Nodejs dependencies
  community.general.npm:
    path: /app
    state: latest

- name: SystemD Setup
  ansible.builtin.include_tasks: "systemd.yml"

- name: Load Schema
  ansible.builtin.include_tasks: "{{schema_type}}-schema.yml"
  when: schema_load